name: CI
on: push
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up updated Node engine
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install -g yarn
      - run: yarn install

      # - name: Install dependencies [YARN install]
      #   uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install

      # - name: Build static files [YARN build]
      #   uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: build
